import { MapObject } from '@models/map-object.interface';

export const MAP_OBJECTS: MapObject[] = [
  {
    id: '1',
    position: { x: 100, y: 100 },
    adjustPosition: { x: 0, y: 0 },
    size: { width: 100, height: 100 },
    backgroundColor: 'red',
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 10,
    zIndex: 3,
    text: '1',
    fontSize: 16,
    fontColor: 'white',
    rotation: 45,
    keepRatio: false,
    borderOpacity: 1,
    borderType: 'solid',
    fillColor: 'red',
    fillOpacity: 1,
    fontType: 'monospace',
    imageUrl: '',
    textColor: 'red',
    textOpacity: 1,
    type: 'rectangle',
  },
  {
    id: '2',
    position: { x: 300, y: 300 },
    adjustPosition: { x: 0, y: 0 },
    size: { width: 200, height: 100 },
    backgroundColor: 'green',
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 0,
    zIndex: 2,
    text: '2',
    fontSize: 16,
    fontColor: 'white',
    rotation: 0,
    keepRatio: false,
    borderOpacity: 1,
    borderType: 'solid',
    fillColor: 'red',
    fillOpacity: 1,
    fontType: 'monospace',
    imageUrl: '',
    textColor: 'red',
    textOpacity: 1,
    type: 'rectangle',
  },
  {
    id: '3',
    position: { x: 500, y: 500 },
    adjustPosition: { x: 0, y: 0 },
    size: { width: 100, height: 100 },
    backgroundColor: 'blue',
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 50,
    zIndex: 2,
    text: '3',
    fontSize: 16,
    fontColor: 'white',
    rotation: 0,
    keepRatio: true,
    borderOpacity: 1,
    borderType: 'solid',
    fillColor: 'red',
    fillOpacity: 1,
    fontType: 'monospace',
    imageUrl: '',
    textColor: 'red',
    textOpacity: 1,
    type: 'circle',
  },
  {
    id: '4',
    position: { x: 1000, y: 400 },
    adjustPosition: { x: 0, y: 0 },
    size: { width: 460, height: 409 },
    backgroundColor: '',
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 0,
    zIndex: 1,
    text: '2',
    fontSize: 16,
    fontColor: 'white',
    rotation: 0,
    keepRatio: true,
    borderOpacity: 1,
    borderType: 'solid',
    fillColor: 'red',
    fillOpacity: 1,
    fontType: 'monospace',
    imageUrl: 'https://img-9gag-fun.9cache.com/photo/aN0gO46_460s.jpg',
    textColor: 'red',
    textOpacity: 1,
    type: 'rectangle',
  },
  {
    id: '5',
    position: { x: 1000, y: 500 },
    adjustPosition: { x: 0, y: 0 },
    size: { width: 100, height: 100 },
    backgroundColor: '',
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 0,
    zIndex: 1,
    text: '2',
    fontSize: 16,
    fontColor: 'white',
    rotation: 0,
    keepRatio: false,
    borderOpacity: 1,
    borderType: 'solid',
    fillColor: 'red',
    fillOpacity: 1,
    fontType: 'monospace',
    imageUrl: '',
    textColor: 'red',
    textOpacity: 1,
    type: 'svg',
    svg: '<svg viewBox="0 0 100 100" height="100%" width="100%" xmlns="http://www.w3.org/2000/svg"><circle fill="yellow" cx="50%" cy="50%" r="50" /><text x="20%" y="50%">Im a SVG</text></svg>',
  },
];
