import { MapObject } from '@models/map-object.interface';

export const MAP_OBJECTS: MapObject[] = [
  {
    id: '1',
    position: { x: 100, y: 100 },
    adjustPosition: { x: 100, y: 100 },
    size: { width: 100, height: 100 },
    backgroundColor: 'red',
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 10,
    zIndex: 3,
    text: '1',
    fontSize: 16,
    fontColor: 'white',
    rotation: 45,
    keepRatio: false,
    borderOpacity: 1,
    borderType: 'solid',
    fillColor: 'red',
    fillOpacity: 1,
    fontType: 'monospace',
    imageUrl: '',
    textColor: 'red',
    textOpacity: 1,
    type: 'rectangle',
  },
  {
    id: '2',
    position: { x: 300, y: 300 },
    adjustPosition: { x: 300, y: 300 },
    size: { width: 200, height: 100 },
    backgroundColor: 'green',
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 0,
    zIndex: 2,
    text: '2',
    fontSize: 16,
    fontColor: 'white',
    rotation: 0,
    keepRatio: false,
    borderOpacity: 1,
    borderType: 'solid',
    fillColor: 'red',
    fillOpacity: 1,
    fontType: 'monospace',
    imageUrl: '',
    textColor: 'red',
    textOpacity: 1,
    type: 'rectangle',
  },
  {
    id: '3',
    position: { x: 500, y: 500 },
    adjustPosition: { x: 500, y: 500 },
    size: { width: 100, height: 100 },
    backgroundColor: 'blue',
    borderColor: 'black',
    borderWidth: 2,
    borderRadius: 50,
    zIndex: 1,
    text: '3',
    fontSize: 16,
    fontColor: 'white',
    rotation: 0,
    keepRatio: true,
    borderOpacity: 1,
    borderType: 'solid',
    fillColor: 'red',
    fillOpacity: 1,
    fontType: 'monospace',
    imageUrl: '',
    textColor: 'red',
    textOpacity: 1,
    type: 'rectangle',
  },
];
